"""Google Calendar integration for adding workouts"""

import os
import json
from datetime import datetime, timedelta
from typing import Optional

# For Google Calendar API
try:
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import Flow
    from googleapiclient.discovery import build
    GOOGLE_AVAILABLE = True
except ImportError:
    GOOGLE_AVAILABLE = False

# Google Calendar OAuth settings
GOOGLE_SCOPES = ['https://www.googleapis.com/auth/calendar.events']


def get_google_auth_url(client_id: str, client_secret: str, redirect_uri: str) -> str:
    """Generate Google OAuth URL"""
    if not GOOGLE_AVAILABLE:
        return None
    
    flow = Flow.from_client_config(
        {
            "web": {
                "client_id": client_id,
                "client_secret": client_secret,
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "redirect_uris": [redirect_uri]
            }
        },
        scopes=GOOGLE_SCOPES,
        redirect_uri=redirect_uri
    )
    
    auth_url, _ = flow.authorization_url(
        access_type='offline',
        include_granted_scopes='true',
        prompt='consent'
    )
    
    return auth_url


def exchange_google_code(code: str, client_id: str, client_secret: str, redirect_uri: str) -> dict:
    """Exchange authorization code for tokens"""
    if not GOOGLE_AVAILABLE:
        return None
    
    flow = Flow.from_client_config(
        {
            "web": {
                "client_id": client_id,
                "client_secret": client_secret,
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "redirect_uris": [redirect_uri]
            }
        },
        scopes=GOOGLE_SCOPES,
        redirect_uri=redirect_uri
    )
    
    flow.fetch_token(code=code)
    credentials = flow.credentials
    
    return {
        "token": credentials.token,
        "refresh_token": credentials.refresh_token,
        "token_uri": credentials.token_uri,
        "client_id": credentials.client_id,
        "client_secret": credentials.client_secret,
        "scopes": list(credentials.scopes)
    }


def save_google_tokens(tokens: dict, filepath: str = ".google_tokens.json"):
    """Save Google tokens to file"""
    with open(filepath, "w") as f:
        json.dump(tokens, f)


def load_google_tokens(filepath: str = ".google_tokens.json") -> Optional[dict]:
    """Load Google tokens from file"""
    try:
        with open(filepath, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return None


def get_calendar_service(tokens: dict):
    """Get Google Calendar API service"""
    if not GOOGLE_AVAILABLE:
        return None
    
    credentials = Credentials(
        token=tokens["token"],
        refresh_token=tokens.get("refresh_token"),
        token_uri=tokens.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=tokens.get("client_id"),
        client_secret=tokens.get("client_secret"),
        scopes=tokens.get("scopes", GOOGLE_SCOPES)
    )
    
    return build('calendar', 'v3', credentials=credentials)


def create_workout_event(
    service,
    title: str,
    description: str,
    details: list[str],
    duration_min: int,
    start_time: Optional[datetime] = None,
    calendar_id: str = 'primary'
) -> dict:
    """Create a calendar event for a workout"""
    
    if start_time is None:
        # Default to tomorrow at 9 AM
        start_time = datetime.now().replace(hour=9, minute=0, second=0, microsecond=0)
        start_time += timedelta(days=1)
    
    end_time = start_time + timedelta(minutes=duration_min)
    
    # Build description with details
    full_description = f"{description}\n\n"
    full_description += "Workout Details:\n"
    for detail in details:
        full_description += f"• {detail}\n"
    full_description += "\n[Generated by WHOOP Training Dashboard]"
    
    event = {
        'summary': f"🏋️ {title}",
        'description': full_description,
        'start': {
            'dateTime': start_time.isoformat(),
            'timeZone': 'Europe/London',  # Will be adjusted based on user
        },
        'end': {
            'dateTime': end_time.isoformat(),
            'timeZone': 'Europe/London',
        },
        'reminders': {
            'useDefault': False,
            'overrides': [
                {'method': 'popup', 'minutes': 30},
            ],
        },
        'colorId': '10',  # Green color
    }
    
    created_event = service.events().insert(calendarId=calendar_id, body=event).execute()
    return created_event


def add_workout_to_calendar(
    tokens: dict,
    workout_title: str,
    workout_description: str,
    workout_details: list[str],
    duration_min: int,
    scheduled_time: Optional[datetime] = None
) -> Optional[str]:
    """Add a workout to Google Calendar, returns event link"""
    
    service = get_calendar_service(tokens)
    if not service:
        return None
    
    try:
        event = create_workout_event(
            service=service,
            title=workout_title,
            description=workout_description,
            details=workout_details,
            duration_min=duration_min,
            start_time=scheduled_time
        )
        return event.get('htmlLink')
    except Exception as e:
        print(f"Error creating calendar event: {e}")
        return None


# ─── ICS File Generation (fallback without Google OAuth) ─────────────────────

def generate_ics_content(
    title: str,
    description: str,
    details: list[str],
    duration_min: int,
    start_time: Optional[datetime] = None
) -> str:
    """Generate ICS file content for a workout"""
    
    if start_time is None:
        start_time = datetime.now().replace(hour=9, minute=0, second=0, microsecond=0)
        start_time += timedelta(days=1)
    
    end_time = start_time + timedelta(minutes=duration_min)
    
    # Format times for ICS
    dtstart = start_time.strftime("%Y%m%dT%H%M%S")
    dtend = end_time.strftime("%Y%m%dT%H%M%S")
    dtstamp = datetime.now().strftime("%Y%m%dT%H%M%SZ")
    
    # Build description
    full_desc = description + "\\n\\n"
    for detail in details:
        full_desc += f"• {detail}\\n"
    
    # Escape special characters
    full_desc = full_desc.replace(",", "\\,").replace(";", "\\;")
    title_escaped = title.replace(",", "\\,").replace(";", "\\;")
    
    ics = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//WHOOP Training Dashboard//EN
BEGIN:VEVENT
DTSTART:{dtstart}
DTEND:{dtend}
DTSTAMP:{dtstamp}
SUMMARY:🏋️ {title_escaped}
DESCRIPTION:{full_desc}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR"""
    
    return ics

